# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('avatar_url', models.URLField(verbose_name='头像')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='token')),
                ('expired_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Account')),
            ],
        ),
        migrations.CreateModel(
            name='WechatAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.SmallIntegerField(verbose_name='订阅标识')),
                ('openid', models.CharField(max_length=100, verbose_name='openid')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('sex', models.SmallIntegerField(choices=[(0, '未知'), (1, '男性'), (2, '女性')], verbose_name='性别')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('country', models.CharField(max_length=100, verbose_name='国家')),
                ('province', models.CharField(max_length=100, verbose_name='省份')),
                ('language', models.CharField(max_length=100, verbose_name='语言')),
                ('headimgurl', models.URLField(verbose_name='头像')),
                ('subscribe_time', models.BigIntegerField(null=True, verbose_name='关注时间')),
                ('unionid', models.CharField(max_length=100, verbose_name='unionid')),
                ('remark', models.CharField(max_length=100, null=True, verbose_name='血液')),
                ('groupid', models.CharField(max_length=100, null=True, verbose_name='分组ID')),
                ('access_token', models.CharField(max_length=255, verbose_name='access_token')),
                ('refresh_token', models.CharField(max_length=255, verbose_name='refresh_token')),
                ('expires_in', models.IntegerField(help_text='access_token接口调用凭证超时时间，单位（秒）', verbose_name='超时时间')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.Account')),
            ],
        ),
    ]
