# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 15:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import wechat.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('avatar_url', models.URLField(verbose_name='头像')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=(wechat.models.CommonModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='评论')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Account')),
            ],
            bases=(wechat.models.CommonModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(verbose_name='分数')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Account')),
            ],
            bases=(wechat.models.CommonModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.TextField(verbose_name='描述')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('n_total_mark', models.BigIntegerField(default=0, verbose_name='总分数')),
                ('n_account_mark', models.BigIntegerField(default=0, verbose_name='打分人数')),
                ('n_account_comment', models.BigIntegerField(default=0, verbose_name='评论人数')),
                ('n_account_vote', models.BigIntegerField(default=0, verbose_name='赞人数')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Account')),
            ],
            bases=(wechat.models.CommonModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Account')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Photo')),
            ],
            bases=(wechat.models.CommonModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WechatAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, verbose_name='openid')),
                ('unionid', models.CharField(max_length=100, verbose_name='unionid')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('sex', models.SmallIntegerField(choices=[(0, '未知'), (1, '男性'), (2, '女性')], verbose_name='性别')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('country', models.CharField(max_length=100, verbose_name='国家')),
                ('province', models.CharField(max_length=100, verbose_name='省份')),
                ('language', models.CharField(max_length=100, verbose_name='语言')),
                ('headimgurl', models.URLField(verbose_name='头像')),
                ('access_token', models.CharField(max_length=255, verbose_name='access_token')),
                ('refresh_token', models.CharField(max_length=255, verbose_name='refresh_token')),
                ('expires_in', models.IntegerField(help_text='access_token接口调用凭证超时时间，单位（秒）', verbose_name='超时时间')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.Account')),
            ],
            bases=(wechat.models.CommonModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='mark',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Photo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Photo'),
        ),
    ]
