# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='wechatauth',
            name='groupid',
        ),
        migrations.RemoveField(
            model_name='wechatauth',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='wechatauth',
            name='subscribe',
        ),
        migrations.RemoveField(
            model_name='wechatauth',
            name='subscribe_time',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
