# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='n_total_watched',
            field=models.BigIntegerField(default=0, verbose_name='查看数'),
        ),
    ]
