# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='n_total_commit',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='n_total_vote',
        ),
    ]
