# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20160717_0326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='n_photo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='n_total_mark',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='n_vote',
            field=models.BigIntegerField(default=0),
        ),
    ]
