# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 04:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wechat.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wechat', '0003_auto_20160720_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=(wechat.models.CommonModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='photo',
            name='n_favorite',
            field=models.BigIntegerField(default=0, help_text='收藏数', verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='n_favorite',
            field=models.BigIntegerField(default=0, help_text='收藏数', verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(help_text='描述', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='n_account_comment',
            field=models.BigIntegerField(default=0, help_text='评论人数', verbose_name='评论人数'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='n_account_mark',
            field=models.BigIntegerField(default=0, help_text='打分人数', verbose_name='打分人数'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='n_account_vote',
            field=models.BigIntegerField(default=0, help_text='赞人数', verbose_name='赞人数'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='n_total_mark',
            field=models.BigIntegerField(default=0, help_text='总分数', verbose_name='总分数'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='n_total_watched',
            field=models.BigIntegerField(default=0, help_text='查看数', verbose_name='查看数'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.URLField(help_text='URL', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(help_text='所有者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar_url',
            field=models.URLField(help_text='头像', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='n_photo',
            field=models.IntegerField(default=0, help_text='我的照片数'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='n_total_mark',
            field=models.BigIntegerField(default=0, help_text='我的总得分数'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='n_vote',
            field=models.BigIntegerField(default=0, help_text='我的总赞数'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(help_text='昵称', max_length=100, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Photo'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
