# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_commit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 26, 15, 31, 55, 364919, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 26, 15, 31, 59, 534713, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 26, 15, 32, 0, 921063, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 26, 15, 32, 2, 285074, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 26, 15, 32, 5, 26988, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 26, 15, 32, 6, 271739, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 26, 15, 32, 7, 707854, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 26, 15, 32, 12, 185525, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 26, 15, 32, 13, 570374, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 26, 15, 32, 14, 841274, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wechatauth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 26, 15, 32, 16, 172154, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wechatauth',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 26, 15, 32, 17, 518152, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
