# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 05:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import wechat.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wechat', '0004_auto_20160724_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('city', models.CharField(max_length=100, null=True, verbose_name='城市')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='国家')),
                ('province', models.CharField(max_length=100, null=True, verbose_name='省份')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(wechat.models.CommonModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='photo',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='photo',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='photo',
            name='province',
            field=models.CharField(max_length=100, null=True, verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 24, 5, 26, 42, 678800, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 24, 5, 26, 46, 714871, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
