# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0005_auto_20160724_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='n_avg_mark',
            field=models.BigIntegerField(default=0, help_text='平均分', verbose_name='平均分'),
        ),
    ]
