# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-29 07:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0008_auto_20160920_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='country',
        ),
        migrations.AddField(
            model_name='photo',
            name='district',
            field=models.CharField(max_length=100, null=True, verbose_name='区'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='district',
            field=models.CharField(max_length=100, null=True, verbose_name='区'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='urls json 列表', verbose_name='URL'),
        ),
    ]
