# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0009_auto_20161029_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatauth',
            name='openid',
            field=models.CharField(max_length=100, unique=True, verbose_name='openid'),
        ),
    ]
