# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0010_auto_20161121_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatauth',
            name='expires_in',
            field=models.IntegerField(help_text='access_token接口调用凭证超时时间，单位（秒）', null=True, verbose_name='超时时间'),
        ),
    ]
