# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 07:51
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=True, help_text='是否接受', verbose_name='是否接受')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='标题', max_length=255, verbose_name='标题')),
                ('content', models.TextField(blank=True, help_text='正文', null=True, verbose_name='正文')),
                ('address', models.CharField(blank=True, help_text='地址', max_length=255, null=True, verbose_name='地址')),
                ('address_location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='地址坐标', null=True, srid=4326, verbose_name='地址坐标')),
                ('started_date', models.DateTimeField(help_text='结束时间', verbose_name='结束时间')),
                ('notify_me', models.IntegerField(default=0, help_text='何时通知我', verbose_name='何时通知我')),
                ('notify_other', models.IntegerField(default=0, help_text='何时通知别人', verbose_name='何时通知别人')),
                ('user', models.ForeignKey(help_text='所有者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='标题', max_length=255, verbose_name='标题')),
                ('content', models.TextField(blank=True, help_text='正文', null=True, verbose_name='正文')),
                ('address', models.CharField(blank=True, help_text='地址', max_length=255, null=True, verbose_name='地址')),
                ('address_location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='地址坐标', null=True, srid=4326, verbose_name='地址坐标')),
                ('started_date', models.DateTimeField(help_text='结束时间', verbose_name='结束时间')),
                ('notify_me', models.IntegerField(default=0, help_text='何时通知我', verbose_name='何时通知我')),
                ('notify_other', models.IntegerField(default=0, help_text='何时通知别人', verbose_name='何时通知别人')),
                ('used_count', models.IntegerField(default=0, help_text='模板使用次数', verbose_name='模板使用次数')),
                ('user', models.ForeignKey(help_text='所有者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='eventuser',
            name='event',
            field=models.ForeignKey(help_text='事件', on_delete=django.db.models.deletion.CASCADE, to='hangout.Schedule'),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='user',
            field=models.ForeignKey(help_text='所有者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
