# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 08:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hangout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='ended_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 9, 8, 8, 22, 589292, tzinfo=utc), help_text='结束时间', verbose_name='结束时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_notified',
            field=models.BooleanField(default=False, help_text='是否已通知', verbose_name='是否已通知'),
        ),
        migrations.AddField(
            model_name='template',
            name='ended_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 9, 8, 8, 26, 861315, tzinfo=utc), help_text='结束时间', verbose_name='结束时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='started_date',
            field=models.DateTimeField(help_text='开始时间', verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='template',
            name='started_date',
            field=models.DateTimeField(help_text='开始时间', verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='template',
            name='used_count',
            field=models.IntegerField(default=1, help_text='模板使用次数', verbose_name='模板使用次数'),
        ),
    ]
