# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hangout', '0002_auto_20161109_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=True, help_text='是否接受', verbose_name='是否接受')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='user',
        ),
        migrations.AddField(
            model_name='schedule',
            name='accepted_count',
            field=models.IntegerField(default=1, help_text='模板使用次数', verbose_name='模板使用次数'),
        ),
        migrations.DeleteModel(
            name='EventUser',
        ),
        migrations.AddField(
            model_name='scheduleuser',
            name='schedule',
            field=models.ForeignKey(help_text='事件', on_delete=django.db.models.deletion.CASCADE, to='hangout.Schedule'),
        ),
        migrations.AddField(
            model_name='scheduleuser',
            name='user',
            field=models.ForeignKey(help_text='所有者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
