# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hangout', '0003_auto_20161109_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.CharField(help_text='获取的二维码ticket，凭借此ticket可以在有效时间内换取二维码。', max_length=255)),
                ('url', models.CharField(help_text='二维码图片解析后的地址，开发者可根据该地址自行生成需要的二维码图片', max_length=255)),
                ('expire_at', models.DateTimeField(help_text='过期时间, 默认当前时间+30天')),
                ('schedule', models.ForeignKey(help_text='事件', on_delete=django.db.models.deletion.CASCADE, to='hangout.Schedule')),
                ('user', models.ForeignKey(help_text='所有者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
