# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangout', '0004_scheduleshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleshare',
            name='expire_at',
            field=models.DateTimeField(help_text='过期时间, 默认当前时间+30天', null=True),
        ),
    ]
