# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangout', '0006_auto_20161116_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='HangoutConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(help_text='key', max_length=255, unique=True, verbose_name='key')),
                ('desc', models.CharField(help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('content', models.TextField(blank=True, help_text='正文', null=True, verbose_name='正文')),
            ],
        ),
    ]
