# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangout', '0007_hangoutconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_notified',
        ),
        migrations.RemoveField(
            model_name='template',
            name='ended_date',
        ),
        migrations.RemoveField(
            model_name='template',
            name='notify_me',
        ),
        migrations.RemoveField(
            model_name='template',
            name='notify_other',
        ),
        migrations.RemoveField(
            model_name='template',
            name='started_date',
        ),
        migrations.AddField(
            model_name='scheduleuser',
            name='is_notified',
            field=models.BooleanField(default=False, help_text='是否已通知', verbose_name='是否已通知'),
        ),
        migrations.AddField(
            model_name='scheduleuser',
            name='notified_date',
            field=models.DateTimeField(help_text='通知时间的记录', null=True, verbose_name='通知时间'),
        ),
        migrations.AddField(
            model_name='template',
            name='duration',
            field=models.IntegerField(default=0, help_text='用时，单位分钟', verbose_name='用时'),
        ),
    ]
