# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-26 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangout', '0008_auto_20161130_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleuser',
            name='notify_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 23, 17, 45, 9, 857731), verbose_name='何时通知'),
            preserve_default=False,
        ),
    ]
